name: EnderPearlAbilities
version: '${project.version}'
main: io.github.henry_yslin.enderpearlabilities.EnderPearlAbilities
api-version: 1.18
depend: [ Citizens, ProtocolLib ]
commands:
  ability:
    description: Commands to manage ender pearl abilities
    usage: |
      /ability query <player name> - Check the abilities of a player
      /ability info <ability code name> - Check the detailed description of an ability
      /ability register <ability code name> - Register an ability for yourself
      /ability unregister <ability code name> - Unregister an ability for yourself
      /ability list - List all available abilities
      /ability config - Check the global configs that are currently active
permissions:
  ability.query:
    description: Check the abilities of a player
    default: op
  ability.info:
    description: Check the detailed description of an ability
    default: true
  ability.register:
    description: Register an ability for yourself
    default: op
  ability.unregister:
    description: Unregister an ability for yourself
    default: op
  ability.list:
    description: List all available abilities
    default: op
  ability.config:
    description: Check the global configs that are currently active
    default: op
  ability.edit:
    description: Allows modification of your own abilities
    default: op
    children:
      ability.register: true
      ability.unregister: true
  ability.*:
    description: Wildcard permission
    default: op
    children:
      ability.query: true
      ability.info: true
      ability.register: true
      ability.unregister: true
      ability.list: true
      ability.config: true
      ability.edit: true