name: EnderPearlAbilities
version: '${project.version}'
main: io.github.henry_yslin.enderpearlabilities.EnderPearlAbilities
api-version: 1.17
depend: [ Citizens, ProtocolLib ]
commands:
  ability:
    description: Commands to manage ender pearl abilities
    usage: |
      /ability query <player name> - Check the abilities of a player
      /ability info <ability code name> - Check the detailed description of an ability
      /ability register <ability code name> - Register an ability for yourself
      /ability unregister <ability code name> - Unregister an ability for yourself
      /ability list - List all available abilities
      /ability config - Check the global configs that are currently active